### ISSUE TITLE
about FFHQ.hdf5

### ISSUE THREAD

**Issue by yiping-tks** [duxiaodan/Fast_text2StyleGAN#1]
Hi, thanks for your great job of this amazing work. I want to reproduce your work in my own dataset, I want to know how did you preprocess your data to create the .hdf5 file?
thanks again!

**Comment by duxiaodan** [comment]
Thank you for your interest in our work! I did some digging and cleaned up my ipynb for encoding ffhq into .hdf5 file. You can find it [here](https://github.com/duxiaodan/Fast_text2StyleGAN/blob/main/encode_ffhq.ipynb). It has been a while so there might be some bugs caused by my cleaning. Please feel free to reopen this issue in case you encounter any. Also, please note that some packages (e.g. clip) I used in the file might have been updated so you'll probably need to modify the code if you have a later version of these packages.
